variable "resource_group_name" {
  type        = string
  description = "Name of the resource group to be imported."
  nullable    = false
}

variable "vnet_location" {
  type        = string
  description = "The location of the vnet to create."
  nullable    = false
}

variable "subnets" {
  type        = list(object({
    name = string,
    subnet_type = string,
    prefix = string,
    service_endpoints = list(string)
    subnet_delegation = map(any)
  }))
  default     = []
  description = "The subnets to create in the vnet. Subnet type can be one of Case Sensitive values (enterprise, private, public, dmz, centralingress, centralegress)"
}

variable "route_table_name" {
  type        = string
  description = "Name of the route table to create."
}

variable "disable_bgp_route_propagation" {
  type        = bool
  default     = false
  description = "Whether disable BGP route propagation on the route table."
}

variable "subnet_enforce_private_link_endpoint_network_policies" {
  type        = map(bool)
  default     = {}
  description = "A map of subnet name to enable/disable private link endpoint network policies on the subnet."
}

variable "subnet_enforce_private_link_service_network_policies" {
  type        = map(bool)
  default     = {}
  description = "A map of subnet name to enable/disable private link service network policies on the subnet."
}

variable "subnet_service_endpoints" {
  type        = map(any)
  default     = {}
  description = "A map of subnet name to service endpoints to add to the subnet."
}

variable "tags" {
  type = map(string)
  default = {
    ENV = "test"
  }
  description = "The tags to associate with your network and subnets."
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}

variable "vnet_name" {
  type        = string
  description = "Name of the vnet to create subnet in."
}
